[package]
name = "rustmart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"
[lib]
crate-type = ["cdylib", "rlib"]
